// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	domain "2023_2_Holi/domain"

	mock "github.com/stretchr/testify/mock"
)

// SeriesRepository is an autogenerated mock type for the SeriesRepository type
type SeriesRepository struct {
	mock.Mock
}

// GetCastNameSeries provides a mock function with given fields: id
func (_m *SeriesRepository) GetCastNameSeries(id int) (domain.Cast, error) {
	ret := _m.Called(id)

	var r0 domain.Cast
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (domain.Cast, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) domain.Cast); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Cast)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCastPageSeries provides a mock function with given fields: id
func (_m *SeriesRepository) GetCastPageSeries(id int) ([]domain.Video, error) {
	ret := _m.Called(id)

	var r0 []domain.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.Video, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.Video); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSeriesByGenre provides a mock function with given fields: genre
func (_m *SeriesRepository) GetSeriesByGenre(genre int) ([]domain.Video, error) {
	ret := _m.Called(genre)

	var r0 []domain.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.Video, error)); ok {
		return rf(genre)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.Video); ok {
		r0 = rf(genre)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(genre)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSeriesCast provides a mock function with given fields: id
func (_m *SeriesRepository) GetSeriesCast(id int) ([]domain.Cast, error) {
	ret := _m.Called(id)

	var r0 []domain.Cast
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.Cast, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.Cast); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Cast)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSeriesData provides a mock function with given fields: id
func (_m *SeriesRepository) GetSeriesData(id int) (domain.Video, error) {
	ret := _m.Called(id)

	var r0 domain.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (domain.Video, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) domain.Video); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Video)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSeriesEpisodes provides a mock function with given fields: id
func (_m *SeriesRepository) GetSeriesEpisodes(id int) ([]domain.Episode, error) {
	ret := _m.Called(id)

	var r0 []domain.Episode
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.Episode, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.Episode); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Episode)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTopRate provides a mock function with given fields:
func (_m *SeriesRepository) GetTopRate() (domain.Video, error) {
	ret := _m.Called()

	var r0 domain.Video
	var r1 error
	if rf, ok := ret.Get(0).(func() (domain.Video, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() domain.Video); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.Video)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSeriesRepository creates a new instance of SeriesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSeriesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SeriesRepository {
	mock := &SeriesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
