// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// SubsRepository is an autogenerated mock type for the SubsRepository type
type SubsRepository struct {
	mock.Mock
}

// CheckSub provides a mock function with given fields: userId
func (_m *SubsRepository) CheckSub(userId int) (time.Time, error) {
	ret := _m.Called(userId)

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (time.Time, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int) time.Time); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Subscribe provides a mock function with given fields: userId
func (_m *SubsRepository) Subscribe(userId int) error {
	ret := _m.Called(userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnSubscribe provides a mock function with given fields: userId
func (_m *SubsRepository) UnSubscribe(userId int) error {
	ret := _m.Called(userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSubsRepository creates a new instance of SubsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubsRepository {
	mock := &SubsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
