// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAuthCheckerServer is an autogenerated mock type for the UnsafeAuthCheckerServer type
type UnsafeAuthCheckerServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAuthCheckerServer provides a mock function with given fields:
func (_m *UnsafeAuthCheckerServer) mustEmbedUnimplementedAuthCheckerServer() {
	_m.Called()
}

// NewUnsafeAuthCheckerServer creates a new instance of UnsafeAuthCheckerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeAuthCheckerServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeAuthCheckerServer {
	mock := &UnsafeAuthCheckerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
