{
 "title": "Node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "up{instance_type='node'}" } }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance)(irate(node_cpu_seconds_total{mode='idle'}[1m])))",
     "legendFormat": "CPU Used"
    },
    {
     "expr": "((node_memory_MemAvailable_bytes) / (node_memory_MemTotal_bytes) * 100)",
     "legendFormat": "Memory Available"
    },
    {
     "expr": "((node_filesystem_avail_bytes{mountpoint='/'}) / (node_filesystem_size_bytes{mountpoint='/'}) * 100)",
     "legendFormat": "Disc Available"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance)(irate(node_cpu_seconds_total{mode='idle'}[1m])))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes) - (node_memory_MemAvailable_bytes))",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Available" }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{mountpoint='/'}) - (node_filesystem_avail_bytes{mountpoint='/'}))",
     "legendFormat": "Used"
    },
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint='/'})",
     "legendFormat": "Available"
    }
   ]
  }
 ]
}