{
 "title": "auth",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"auth:3001\"}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hits{path!=\"/metrics\", instance=\"auth:3001\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RP24H",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(hits{path!=\"/metrics\", instance=\"auth:3001\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(floor(sum(increase(hits{instance=\"auth:3001\",status=~'2..'}[24h]))))",
     "legendFormat": "2xx"
    },
    {
     "expr": "(floor(sum(increase(hits{instance=\"auth:3001\",status=~'3..'}[24h]))))",
     "legendFormat": "3xx"
    },
    {
     "expr": "(floor(sum(increase(hits{instance=\"auth:3001\",status=~'4..'}[24h]))))",
     "legendFormat": "4xx"
    },
    {
     "expr": "(floor(sum(increase(hits{instance=\"auth:3001\",status=~'5..'}[24h]))))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Duration 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum  by (le) (rate(duration_bucket{status=~\"2..\", instance=\"auth:3001\"}[$__rate_interval])))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.90, sum  by (le) (rate(duration_bucket{status=~\"2..\", instance=\"auth:3001\"}[$__rate_interval])))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.75, sum  by (le) (rate(duration_bucket{status=~\"2..\", instance=\"auth:3001\"}[$__rate_interval])))",
     "legendFormat": "75"
    },
    {
     "expr": "histogram_quantile(0.50, sum  by (le) (rate(duration_bucket{status=~\"2..\", instance=\"auth:3001\"}[$__rate_interval])))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "Duration Err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum  by (le) (rate(duration_bucket{status=~\"4..|5..\", instance=\"auth:3001\"}[$__rate_interval])))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.90, sum  by (le) (rate(duration_bucket{status=~\"4..|5..\"}[$__rate_interval])))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.75, sum  by (le) (rate(duration_bucket{status=~\"4..|5..\"}[$__rate_interval])))",
     "legendFormat": "75"
    },
    {
     "expr": "histogram_quantile(0.50, sum  by (le) (rate(duration_bucket{status=~\"4..|5..\"}[$__rate_interval])))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "increase(hits{instance=\"auth:3001\", path!=\"/metrics\"}[1m])",
     "legendFormat": "{{path}} {{status}}"
    }
   ]
  }
 ]
}