{
 "title": "auth",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hits{path!=\"/metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RP24H",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(hits{path!=\"/metrics\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum  by (le) (rate(duration_bucket{status=~\"2..\"}[$__rate_interval])))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.90, sum  by (le) (rate(duration_bucket{status=~\"2..\"}[$__rate_interval])))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.75, sum  by (le) (rate(duration_bucket{status=~\"2..\"}[$__rate_interval])))",
     "legendFormat": "75"
    },
    {
     "expr": "histogram_quantile(0.50, sum  by (le) (rate(duration_bucket{status=~\"2..\"}[$__rate_interval])))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "Duration Err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum  by (le) (rate(duration_bucket{status=~\"4..|5..\"}[$__rate_interval])))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.90, sum  by (le) (rate(duration_bucket{status=~\"4..|5..\"}[$__rate_interval])))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.75, sum  by (le) (rate(duration_bucket{status=~\"4..|5..\"}[$__rate_interval])))",
     "legendFormat": "75"
    },
    {
     "expr": "histogram_quantile(0.50, sum  by (le) (rate(duration_bucket{status=~\"4..|5..\"}[$__rate_interval])))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rate(hits[5m])", "legendFormat": "{{path}} {{status}}" }
   ]
  }
 ]
}