// Code generated by mockery v2.35.1. DO NOT EDIT.

package domain

import mock "github.com/stretchr/testify/mock"

// MockFilmRepository is an autogenerated mock type for the FilmRepository type
type MockFilmRepository struct {
	mock.Mock
}

// GetFilmsByGenre provides a mock function with given fields: genre
func (_m *MockFilmRepository) GetFilmsByGenre(genre string) ([]Film, error) {
	ret := _m.Called(genre)

	var r0 []Film
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]Film, error)); ok {
		return rf(genre)
	}
	if rf, ok := ret.Get(0).(func(string) []Film); ok {
		r0 = rf(genre)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Film)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(genre)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockFilmRepository creates a new instance of MockFilmRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilmRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilmRepository {
	mock := &MockFilmRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
